services:
  weather_bot_tg:
    build: .
    container_name: openmeteo_bot
#    restart: unless-stopped
#    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./data:/app/data
      - ./Images:/app/Images
    env_file:
      - .env